fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Chaplean\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: chaplean_user_registration
            validation_groups: [ ChapleanRegistration ]
    profile:
        form:
            type: chaplean_user_profile
            validation_groups: [ ChapleanProfile ]
    service:
        user_manager: chaplean_user.user_manager