chaplean_user_index:
    path: /

chaplean_user_register:
    path: /register
    defaults: { _controller: ChapleanUserBundle:Registration:register }
    options:
          expose: true

chaplean_user_confirm:
    path: /retrieve/key/{token}
    defaults: { _controller: ChapleanUserBundle:Registration:retrieve }
    options:
        expose: true

chaplean_user_forgot:
    path: /forgot
    defaults: { _controller: ChapleanUserBundle:Registration:forgot }

chaplean_user_login:
    path: /login
    defaults: { _controller: ChapleanUserBundle:Security:login }

chaplean_user_profile:
    path: /profile
    defaults: { _controller: ChapleanUserBundle:Profile:index }

chaplean_user_password_request_reset:
    path: /password/request_reset
    defaults: { _controller: ChapleanUserBundle:Password:requestResetPasswordForm }

chaplean_user_password_set_passwerd:
    path: /password/set
    defaults: { _controller: ChapleanUserBundle:Password:setPasswordForm }
