security:
    access_control:
        - { path: ^/index$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot,         role: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: app_front
                login_path: /login
                use_forward: false
                remember_me: true
                use_referer: true
                success_handler: chaplean_user.authentication.handler_http
                failure_handler: chaplean_user.authentication.handler_http
                csrf_provider: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            anonymous:    true

    providers:
        app_front:
            id: chaplean_user.user.provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
