security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chaplean_user_provider:
            id: chaplean_user.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: chaplean_user_provider
                login_path: /login
                use_forward: false
                remember_me: true
                use_referer: true
                success_handler: chaplean_user.authentication.handler_http
                failure_handler: chaplean_user.authentication.handler_http
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            anonymous:    true
