security:
    encoders:
        Chaplean\Bundle\UserBundle\Doctrine\User: { id: chaplean_user.encoder.password }

    providers:
        user_provider:
            id: chaplean_user.user_provider.email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

        main:
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: /login
                use_forward: false
                remember_me: true
                use_referer: true
                success_handler: chaplean_use.authentication.handler
                failure_handler: chaplean_use.authentication.handler
                csrf_provider: security.csrf.token_manager
            logout:       true
            anonymous:    true