parameters:
    chaplean_user.authentication.handler.class: Chaplean\Bundle\UserBundle\Handler\AuthenticationHandler
    chaplean_user.entity.user.class: Chaplean\Bundle\UserBundle\Doctrine\User
    chaplean_user.user.provider.class: Chaplean\Bundle\UserBundle\Provider\UserProvider

services:
    chaplean_user.registration.form.type:
        class: Chaplean\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: chaplean_user_registration }

    chaplean_user.user_manager:
        class: Chaplean\Bundle\UserBundle\Doctrine\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.email_canonicalizer, @fos_user.util.username_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]

    chaplean_user.registration:
        class: Chaplean\Bundle\UserBundle\Utility\Registration
        arguments: [@service_container]

    chaplean_user.security:
        class: Chaplean\Bundle\UserBundle\Utility\Security
        arguments: [@service_container]

    chaplean_user.authentication.handler:
            class:  %chaplean_user.authentication.handler.class%
            arguments:  [@router, @security.token_storage, @service_container]

    chaplean_user.encoder.password:
        class: Chaplean\Bundle\UserBundle\Encoder\PasswordEncoder

    chaplean_user.user.provider:
            class: %chaplean_user.user.provider.class%
            arguments: [@chaplean_sso_server.user.repository]