parameters:
    chaplean_user_scurity.component.authentication.handler.login_failure_handler.class: Chaplean\Bundle\UserBundle\Handler\AuthenticationHandler

services:
    chaplean_user.registration.form.type:
        class: Chaplean\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: chaplean_user_registration }
    authentication_handler:
        class: Chaplean\Bundle\UserBundle\Handler\AuthenticationHandler
        arguments: [@router, @security.context, @service_container]
    chaplean_user.user_manager:
        class: Chaplean\Bundle\UserBundle\Doctrine\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.email_canonicalizer, @fos_user.util.username_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]
    chaplean_user.registration:
        class: Chaplean\Bundle\UserBundle\Utility\Registration
        arguments: [@service_container]
    chaplean_user.security:
        class: Chaplean\Bundle\UserBundle\Utility\Security
        arguments: [@service_container]
#    chaplean_user_scurity.component.authentication.handler.login_failure_handler:
#            class:  %chaplean_user_scurity.component.authentication.handler.login_failure_handler.class%
#            arguments:  [@router, @service_container]
#            tags:
#                - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }