parameters:
    chaplean_user.user.provider.class: Chaplean\Bundle\UserBundle\Provider\UserProvider

services:
    chaplean_user.user.manager:
        class: Doctrine\ORM\EntityManager
        factory: [@doctrine, getManagerForClass]
        arguments: [%chaplean_user.entity.user.class%]

    chaplean_user.user.repository:
        class: Chaplean\Bundle\UserBundle\Repository\UserRepository
        factory: [@chaplean_user.user.manager, getRepository]
        arguments: [%chaplean_user.entity.user.class%]

    chaplean_user.user.provider:
        class: %chaplean_user.user.provider.class%
        arguments: [@chaplean_user.user.repository]

    chaplean_user.registration.form.type:
        class: Chaplean\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: chaplean_user_registration }

    chaplean_user.user_manager:
        class: Chaplean\Bundle\UserBundle\Doctrine\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.email_canonicalizer, @fos_user.util.username_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]

    chaplean_user.registration:
        class: Chaplean\Bundle\UserBundle\Utility\Registration
        arguments: [@service_container]

    chaplean_user.security:
        class: Chaplean\Bundle\UserBundle\Utility\Security
        arguments: [@service_container]

    chaplean_user.authentication.handler:
            class:  Chaplean\Bundle\UserBundle\Handler\AuthenticationHandler
            arguments:  [@doctrine, @router.default, @session, @chaplean_user.user_manager, @translator.default, @templating.engine.twig, %chaplean_user%]

    chaplean_user.encoder.password:
        class: Chaplean\Bundle\UserBundle\Encoder\PasswordEncoder
