image: chaplean/php:7.1-no-xdebug

services:
    - name: chaplean/mysql:mariadb10.1
      alias: mysql

variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: app_user
    MYSQL_PASSWORD: app_password
    MYSQL_DATABASE: test_database

cache:
    paths:
        - bin/
        - vendor/

before_script:
    - mkdir -p /root/.ssh
    - echo -e "Host *\n\tForwardAgent yes\n\n" > /root/.ssh/config
    - echo "$CHAPLEAN_DEPLOY_KEY" >> /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
    - echo "$CHAPLEAN_KNOWN_HOSTS" >> /root/.ssh/known_hosts && chmod 0600 /root/.ssh/known_hosts
    - eval `ssh-agent -s`
    - ssh-add

test:
    stage: test
    script:
        - cp app/config/parameters.yml.dist app/config/parameters.yml
        - composer install --prefer-dist --no-interaction
        - php ./bin/phpunit --configuration phpunit.xml.dist --dump-xdebug-filter phpunit-filter.php
        - php -d zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so ./bin/phpunit --prepend phpunit-filter.php --configuration phpunit.xml.dist --colors=never --coverage-text --coverage-html coverage
    artifacts:
        paths:
            - coverage/
        expire_in: 1 day

deploy:
    stage: deploy
    script:
        - ssh chaplean@satis.chaplean.coop /home/www/chaplean.coop/satis/bin/satis build /home/www/chaplean.coop/satis/satis.json /home/www/chaplean.coop/satis/web
