imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ChapleanUserBundle/Resources/config/config.yml }

framework:
    translator:      { fallback: '%locale%' }
    secret:          'S€cR3t'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: true
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    profiler: { only_exceptions: false }
    serializer:
        enable_annotations: true


# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug:          '%use_assetic_debug%'
    use_controller: '%use_assetic_controller%'
    bundles:        []
    ruby: %ruby.bin%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass.bin%
            apply_to: '\.scss'
        compass:
            bin: %compass.bin%
            no_line_comments: true
    assets:
        bootstrap_fonts_woff:
            inputs:
                - '@ChapleanCmsBundle/Resources/public/libs/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff'
            output: fonts/bootstrap/glyphicons-halflings-regular.woff
        bootstrap_fonts_ttf:
            inputs:
                - '@ChapleanCmsBundle/Resources/public/libs/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf'
            output: fonts/bootstrap/glyphicons-halflings-regular.ttf
        bootstrap_fonts_svg:
            inputs:
                - '@ChapleanCmsBundle/Resources/public/libs/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.svg'
            output: fonts/bootstrap/glyphicons-halflings-regular.svg
        bootstrap_fonts_eot:
            inputs:
                - '@ChapleanCmsBundle/Resources/public/libs/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.eot'
            output: fonts/bootstrap/glyphicons-halflings-regular.eot
        font-awesome-otf:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        font-awesome-woff2:
            inputs: '@ChapleanCmsBundle/Resources/public/libs/components-font-awesome/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'

monolog:
    handlers:
        main:
            type:   stream
            path:   '%kernel.logs_dir%/%kernel.environment%.log'
            level:  info
        console:
            type:   console
            bubble: false


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     3306
        dbname:   test_database
        user:     root
        password: %database_password%
        charset:  UTF8
        server_version: 5.5
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: user
        entity_managers:
            user:
                mappings:
                    ChapleanUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

chaplean_user:
    controller:
        index_route: chaplean_user_index
