imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@ChapleanUserBundle/Resources/config/config.yml' }

framework:
    test: ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: true
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    serializer:
        enable_annotations: true
    session:
        storage_id: session.storage.mock_file
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    profiler:
        collect: false


# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:   stream
            path:   '%kernel.logs_dir%/%kernel.environment%.log'
            level:  info
        console:
            type:   console

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                path:     '%kernel.cache_dir%/test.db'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                server_version: 5.6
            logging: null
            profiling: null
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: user
        entity_managers:
            user:
                mappings:
                    ChapleanUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: file }

chaplean_mailer:
    bcc_address: 'user-bundle@chaplean.coop'
    sender_address: 'user-bundle@chaplean.coop'
    sender_name: 'Chaplean'
    subject:
        prefix: '[TEST]'
    test: true

chaplean_user:
    entity:
        user:
            class: Chaplean\Bundle\UserBundle\Entity\DummyUser
    controller:
        index_route: chaplean_user_index

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            -
                path: '^/rest'
                priorities: ['json']
                fallback_format: json
                prefer_extension: false
            -
                path: '^/'
                priorities: ['text/html', 'text/css', '*/*']
                fallback_format: html
                prefer_extension: true
    view:
        formats:
            rss: false
            json: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: false
    serializer:
        serialize_null: true
