chaplean_user:
    resource: '@ChapleanUserBundle/Resources/config/routing.yml'

chaplean_user_api:
    resource: '@ChapleanUserBundle/Resources/config/routing_rest.yml'
    type: rest
    prefix: /api/
