imports:
    - { resource: @ChapleanUserBundle/Resources/config/security.yml }

security:
    encoders:
        Chaplean\Bundle\UserBundle\Entity\DummyUser:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000

    firewalls:
        main:
            form_login:
                success_handler: chaplean_user.authentication.handler_http
                failure_handler: chaplean_user.authentication.handler_http