imports:
    - { resource: @ChapleanUserBundle/Resources/config/security.yml }

security:
    encoders:
        Chaplean\Bundle\UserBundle\Entity\DummyUser:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000